@startuml

class Tablero {
    - [][] coordenadas: Coordenada
    - n : int // tamaño del tablero
    - Tablero(int size) : constructor
        '   -> inicializa objetos Coordenada en coordenadas
    - mostrarTablero() : void
        '   -> mostrarTablero: imprime el tablero, validando: coord.getBarco(), coord.isTocado()
    - colocarBarco(int x, int y, Barco) : void
        '   -> Coordenas.setBarco, ¿¿¿ barco.agregarCoordenada ???
    - atacar(int x, int y) : bool
        '   -> Coordenas.setBarco, coord.setTocado(true), coord.getBarco()->recibirGolpe()
    - todosBarcosHundidos() : bool
        '   -> return all barco.isHundido()
    - getSize(): int
        '   -> return n
}

class Coordenada {
    - letra : str
    - numero : int
    - Barco: Barco, default=null
    - tocado : bool, default=false
    - Coordenada() : constructor
        '   
    - Coordenada(str letra, int numero) : constructor
        '   -> letra_, numero_
    - getLetra() : str
        '   -> return letra
    - getNumero() : int
        '   -> return numero
    - isTocado() : bool
        '   -> return tocado
    - getBarco() : Barco
        '   -> return barco
    - setBarco(Barco) : void
        '   -> this->barco = barco
    - setTocado() : void
        '   -> this->tocado = tocado
}

Tablero "1" o-- "0..*" Coordenada

class Barco {
    - longitud : int //n coordenadas que ocupa
    - horizontal : bool // orientacion
    - hundido : bool, default=false
    - contGolpes : int, default=0
    - Barco(int longitud, bool horizontal) : constructor
        '   -> longitud_, horizontal_
    - verificarHundido() : bool
        '   -> return contGolpes == longitud
    - recibirGolpe() : void
        '   -> contGolpes++, validar si hundido asignar = true
    - getLongitud() : int
        '   -> return longitud
    - isHorizontal() : bool
        '   -> return horizontal
    - isHundido() : bool
        '   -> return hundido

}

Coordenada "1" o-- "0..*" Barco

class Jugador {
    - nombre : str
    - tablero : Tablero
    ' - [] barcos : Barco
    ' - [] disparos : Coordenada
    - Jugador(str nombre, Tablero tablero) : constructor
        '   -> nombre_, tablero_
    - getNombre() : str
    - getTablero() : Tablero
    - colocarBarco(int x, int y, Barco) : void
    - atacar(int x, int y) : bool
    - todosBarcosHundidos() : bool
}

class Usuario {
    - colocarBarco(int x, int y, Barco& barco) override: bool
    - atacar(int x, int y) override: bool
}

class Maquina {
    - colocarBarco(int x, int y, Barco& barco) override: bool
    - atacar(int x, int y) override: bool
}

Usuario --|> Jugador
Maquina --|> Jugador

Jugador "1" o-- "1" Tablero

class Juego {
    - jugador1: Jugador
    - jugador2: Jugador
    + jugar()
}

Juego "1" o-- "1" Jugador

@enduml