@startuml


class Tablero {
}

class Jugador {
}

Jugador o-- Tablero

class Maquina {
}

class Usuario{
}

Maquina --> Jugador
Usuario --> Jugador

class Barco {
    - size: Int
    - posiciones: vector<Coordenada>
    + getPosiciones(): vector<Coordenada>
    + addPosicion(Coordenada): void
}

Tablero o-- Barco

' Casillero=Coordenada=Celda
class Celda{
    - estado: Estado
    + getEstado(): Estado
    + setEstado(Estado): void
}

Tablero o-- Celda

class Partida{
}

Partida o-- Jugador

class Archivo{
}

Partida o-- Archivo

@enduml